language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t gellert/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gellert/react-test npm test

after_success:
  - docker build -t gellert/complex-client ./client
  - docker build -t gellert/complex-nginx ./nginx
  - docker build -t gellert/complex-server ./server
  - docker build -t gellert/worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  - docker push gellert/complex-client
  - docker push gellert/complex-nginx
  - docker push gellert/complex-worker
  - docker push gellert/complex-server
